### PR TITLE
feat: add additional check for captcha verification status

### PR DESCRIPTION
**Pull request by serozhenka**
This PR aims to fix issue #7 by introducing an additional check for a hidden element with id = `tiktok-verify-ele` which indicates a successful verification

### CODE REVIEW

**Review by gbiz123 — COMMENTED** [review]
Looks good but a little concerned about the way it's handled in `SelenimSolver`. From what I understand, when tiktok-verify-ele is **not** present, we want to return True.

```py
if self.chromedriver.find_elements(By.ID, verification_element_id):
                return True
```
This seems to return True if the element is present.

One more comment before merging in... In each individual solve function e.g. `solve_rotate()` please bring back the 5 second wait/sleep. This is to avoid immediately resending the same image after failing the challenge if that makes sense.

**Comment by gbiz123** [comment]
I am also wondering how robust the strategy of using `any()` is. I am worried that there may be a delay between the solution and the time that the verify element disappears, so immediately testing for its presence might lead to false positives. A suggested alternative may be to use the `tiktok-verify-ele` selector as a second check, if the first check fails, to avoid false positives

**Comment by gbiz123** [comment]
Last thing, as i'm not at my computer and can't check at the moment. Can you verify that `tiktok-verify-ele` is only present after successful verification? If it's present before verification, or on failure, there will be false positives. If I remember correctly, this element is present throughout the entire verification

**Comment by serozhenka** [comment]
> One more comment before merging in... In each individual solve function e.g. solve_rotate() please bring back the 5 second wait/sleep. This is to avoid immediately resending the same image after failing the challenge if that makes sense.

Makes sense, but won't the image reload itself when doing a lot of sleeping in `_check_captcha_success`?

> I am also wondering how robust the strategy of using any() is. I am worried that there may be a delay between the solution and the time that the verify element disappears, so immediately testing for its presence might lead to false positives. A suggested alternative may be to use the tiktok-verify-ele selector as a second check, if the first check fails, to avoid false positives

You are right, it doesn't disappear right off.
I'll make it a second of the checks in the sync playwright driver. Async playwright checks both conditions "simultaneously" and selenium one does a lot of checks, so it doesn't matter for them.

> Can you verify that tiktok-verify-ele is only present after successful verification? If it's present before verification, or on failure, there will be false positives. If I remember correctly, this element is present throughout the entire verification

Yes, it's present throughout the whole verification, but it has no content only after the successful verification has happened. In playwright solver I did an explicit check for whether the element is hidden (which includes it being present and having `display: none` CSS attribute). I will fix the selenium solver, so not only the presence is checked

**Comment by serozhenka** [comment]
@gbiz123 fixed the last 2 comments.
kindly waiting on the feedback for the first one

**Comment by gbiz123** [comment]
>> Makes sense, but won't the image reload itself when doing a lot of sleeping in `_check_captcha_success`?

Previously this was the case, but my impression was thay since we're using `expect()` it will return as soon as we get a result, and upon failure the next iteration of the loop will execute immediately.  Is this covered by the 5000ms timeout you added?

Everything else sounds good. I can pull and run the pytest when it's next convenient for me. 

Unrelated, but are you able to use this as a working solution while waiting for the next release? You can do a local pip install with `pip install -e .`

**Comment by serozhenka** [comment]
> Previously this was the case, but my impression was thay since we're using expect() it will return as soon as we get a result, and upon failure the next iteration of the loop will execute immediately. Is this covered by the 5000ms timeout you added?

OK, I will just add the sleeps. They don't matter much for me and it should be safer for everyone.

> Unrelated, but are you able to use this as a working solution while waiting for the next release? You can do a local pip install with pip install -e .

I am currently using something similar to the solution in the PR by monkey-patching the `_check_captcha_status`. But it would be really great to have it released, so I don't have to do that:)

**Comment by serozhenka** [comment]
Done, when you'll have a chance to test this stuff?

**Comment by gbiz123** [comment]
> Done, when you'll have a chance to test this stuff?

New release should be ready in 4-5 hours

**Comment by gbiz123** [comment]
It looks like the code works for puzzle and rotate, but it gives a false positive on shapes (3d)

**Comment by gbiz123** [comment]
> It looks like the code works for puzzle and rotate, but it gives a false positive on shapes (3d). I am going to try using `captcha-disable-scroll` class instead of `tiktok-verify-ele` to check

This seems to have worked. Gonna update the rest now

**Comment by gbiz123** [comment]
I am going to get rid of `_check_captcha_success()` altogether actually, and just use `if not captcha_is_present()`, which greatly simplifies things

**Comment by gbiz123** [comment]
Alright, I wound up changing the route of implementation in the PlaywrightSolver and AsyncPlaywrightSolver from your initial suggestion a bit, but I think it works pretty well as it's passing pytest and doesn't show false positives. Essentially I just check that the captcha scroll lock wrapper is NOT there, and use that to verify success. Please install latest version with `pip install --upgrade tiktok-captcha-solver` and let me know how it goes for you.

**Comment by serozhenka** [comment]
works fine for me, thank you!

**Pull request merged**
